name: Android CI

on:
  push:
    branches: [ "master", "*" ]
  pull_request:
    branches: [ "master" , "*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create local.properties
      run: touch local.properties
    - name: Set API Keys
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> local.properties
        echo "Here_API_KEY=${{ secrets.HERE_API_KEY }}" >> local.properties
        echo "Places_API_KEY=${{ secrets.PLACES_API_KEY }}" >> local.properties

    - name: Build with Gradle
      run: ./gradlew build
      
